[package]
name = "facturx-create"
version = "0.9.0"
edition = "2021"

[lib]
name = "facturx_create"
path = "src/lib.rs"

[[bin]]
name = "facturx-create"
path = "src/main.rs"

[[bin]]
name = "test_pdf"
path = "src/bin/test_pdf.rs"

[dependencies]
axum = { version = "0.7", features = ["multipart"] }
tokio = { version = "1.0", features = ["full"] }
tera = "1.20"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"    # Pour la gestion des dates
krilla = "0.6"    # Pour générer PDF/A-3 avec polices embarquées
xml-rs = "0.8"    # Pour XML Factur-X
tower = "0.4"
tower-http = { version = "0.5", features = ["fs"] }
