[package]
name = "facturx-create"
version = "0.9.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["multipart"] }
tokio = { version = "1.0", features = ["full"] }
tera = "1.20"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
chrono = "0.4"    # Pour la gestion des dates
printpdf = { version = "0.8", features = ["jpeg"] }  # Pour générer PDF
lopdf = "0.37"    # Pour embarquer XML dans PDF (Factur-X)
xml-rs = "0.8"    # Pour XML Factur-X
tower = "0.4"
tower-http = { version = "0.5", features = ["fs"] }
